/** User supplied video thumbnails used throughout the public landing pages. */
export const landingMedia = [
  { image: "/landing/user-thumbnails/play-smarter.jpg", label: "Play smarter", kind: "Sport", prompt: "Make a sports story about the decisions that change a game." },
  { image: "/landing/user-thumbnails/people-and-robots.jpg", label: "When people meet machines", kind: "Technology", prompt: "Explain how people and AI are reshaping the way we work and create." },
  { image: "/landing/user-thumbnails/learn-anything.jpg", label: "Curiosity can change everything", kind: "Education", prompt: "Create an engaging story about how people learn." },
  { image: "/landing/user-thumbnails/781-years.jpg", label: "A remarkable stretch of history", kind: "History", prompt: "Tell an illustrated history story spanning centuries." },
  { image: "/landing/user-thumbnails/boring-history.jpg", label: "History, told a new way", kind: "History", prompt: "Turn an overlooked moment in history into a captivating video." },
  { image: "/landing/user-thumbnails/napoleon.jpg", label: "Napoleon in a minute", kind: "Biography", prompt: "Create a concise, cinematic portrait of Napoleon Bonaparte." },
  { image: "/landing/user-thumbnails/house-of-deception.jpg", label: "Inside the house of deception", kind: "Documentary", prompt: "Create a documentary about an infamous criminal empire." },
  { image: "/landing/user-thumbnails/protect-your-goals.jpg", label: "Protect your focus", kind: "Personal growth", prompt: "Make a thoughtful video about staying focused on your goals." },
  { image: "/landing/user-thumbnails/mindset-transformation.jpg", label: "A mindset can change", kind: "Psychology", prompt: "Tell an encouraging story about changing your mindset." },
  { image: "/landing/user-thumbnails/indian-army-history.jpg", label: "A battle in Indian history", kind: "History", prompt: "Create a richly illustrated documentary about a turning point in Indian history." },
  { image: "/landing/user-thumbnails/maratha-royalty.jpg", label: "The Maratha story", kind: "History", prompt: "Create a cinematic historical story about the Maratha era." },
  { image: "/landing/user-thumbnails/dangerous-minds.jpg", label: "The minds that shaped our world", kind: "Ideas", prompt: "Explore the work and ideas of influential modern thinkers." },
  { image: "/landing/user-thumbnails/the-day-you-quit.jpg", label: "The day everything changed", kind: "Work & life", prompt: "Tell a character-led story about making a difficult career change." },
  { image: "/landing/user-thumbnails/leonardo-and-art.jpg", label: "Leonardo’s curious mind", kind: "Art & science", prompt: "Create an illustrated biography of Leonardo da Vinci." },
  { image: "/landing/user-thumbnails/alexander-the-great.jpg", label: "Alexander the Great", kind: "History", prompt: "Tell the story of Alexander the Great and the world he changed." },
  { image: "/landing/user-thumbnails/graphic-design.jpg", label: "Design with a point of view", kind: "Design", prompt: "Make a visual story about the art of graphic design." },
  { image: "/landing/user-thumbnails/the-architecture-of-wealth.jpg", label: "The architecture of wealth", kind: "Business", prompt: "Explain how the world's wealthiest people build and preserve fortunes." },
  { image: "/landing/user-thumbnails/fail-learn-repeat.jpg", label: "Fail. Learn. Repeat.", kind: "Ideas", prompt: "Create an uplifting story about learning through failure." },
  { image: "/landing/user-thumbnails/ponzi-scheme.jpg", label: "How a Ponzi scheme works", kind: "Business", prompt: "Explain the warning signs and mechanics of a Ponzi scheme." },
  { image: "/landing/user-thumbnails/forensic-science.jpg", label: "Inside forensic science", kind: "Science", prompt: "Make an accessible documentary about forensic science." },
  { image: "/landing/user-thumbnails/visual-storytelling.jpg", label: "The craft of visual storytelling", kind: "Design", prompt: "Show how a visual editor builds an engaging story." },
] as const;
