"use client";
import { useEffect, useMemo, useState } from 'react';
import { Play, Pause, RotateCcw, Volume2, VolumeX, Sparkles } from 'lucide-react';
import { HtmlTemplateFrame } from '@hanuman/video-engine/preview';
import { createPressCutoutTemplate } from '@hanuman/video-engine/press-cutout';
import { NativeCueAudio } from '@/components/editor/canvas/native-cue-audio';
import type { BrandProfile } from '@/lib/brand-profiles';
import { Button } from '@/components/ui/button';
import { UploadedTemplates } from "./uploaded-templates";
const scene={title:'The minds that changed our world',highlight:'changed our world',subtitle:'Every breakthrough begins with someone willing to ask a different question.',eyebrow:'The story behind the idea',source_label:'Illustrative documentary preview'};
export function MotionGraphicsTab({profile,onChange}:{profile:BrandProfile;onChange:(patch:Partial<BrandProfile>)=>void}) {
 const prefs:NonNullable<BrandProfile['motionGraphics']>=profile.motionGraphics??{enabled:false,mode:'selected',templateId:'press-cutout-v1',soundEnabled:true,intensity:'cinematic'};
 const patch=(value:Partial<typeof prefs>)=>onChange({motionGraphics:{...prefs,...value}});
 const [time,setTime]=useState(0);const [playing,setPlaying]=useState(false);const [muted,setMuted]=useState(false);const [error,setError]=useState('');
 const template=useMemo(()=>createPressCutoutTemplate({profileId:profile.id,soundEnabled:prefs.soundEnabled}),[profile.id,prefs.soundEnabled]);
 const previewScene=useMemo(()=>({...scene,motion_intensity:prefs.intensity}),[prefs.intensity]);
 useEffect(()=>{if(!playing)return;let frame=0;let prior=performance.now();const tick=(now:number)=>{const delta=(now-prior)/1000;prior=now;setTime(t=>{if(t+delta>=10){setPlaying(false);return 10;}return t+delta;});frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[playing]);
 return <><section className="mb-5 rounded-2xl border border-border bg-card p-5"><label htmlFor="motion-selection-mode" className="block text-sm font-semibold">Production agent motion graphics</label><p className="mt-1 text-sm text-muted-foreground">Choose which graphics the main video agent may create or use.</p><select id="motion-selection-mode" value={prefs.mode??'selected'} onChange={e=>patch({mode:e.target.value as NonNullable<typeof prefs.mode>})} className="mt-4 w-full rounded-xl border border-input bg-background px-3 py-3 text-sm"><option value="selected">Selected templates only</option><option value="auto">Auto — templates or original scene graphics</option><option value="custom">Custom — original graphics for this story</option><option value="none">No motion graphics</option></select><p className="mt-2 text-xs text-muted-foreground">In selected mode, only templates enabled below are available. Auto and custom keep your narration, language and scene facts.</p></section><UploadedTemplates profile={profile} onChange={onChange}/><section className="flex flex-col gap-5 rounded-2xl border border-border bg-card p-5 sm:p-6">
  <div className="flex items-start justify-between gap-4"><div><h2 className="flex items-center gap-2 text-base font-semibold"><Sparkles className="size-4 text-primary"/>Press Cutout</h2><p className="mt-1 text-sm text-muted-foreground">An editorial headline, paper collage and a cinematic camera push.</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs text-primary">HTML · CSS · GSAP</span></div>
  <div className="relative aspect-video overflow-hidden rounded-xl border border-border"><HtmlTemplateFrame template={template} seconds={time} scene={previewScene} onError={setError}/></div>
  <div className="flex flex-wrap items-center gap-3"><Button size="sm" variant="outline" onClick={()=>{if(time>=10)setTime(0);setPlaying(!playing);}}>{playing?<Pause/>:<Play/>}{playing?'Pause':'Play preview'}</Button><Button size="icon-sm" variant="ghost" aria-label="Restart preview" onClick={()=>{setTime(0);setPlaying(true);}}><RotateCcw/></Button><input aria-label="Preview position" type="range" min="0" max="10" step="0.01" value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value));}} className="min-w-24 flex-1 accent-primary"/><span className="text-xs tabular-nums text-muted-foreground">{time.toFixed(1)} / 10s</span><Button size="icon-sm" variant="ghost" aria-label={muted?'Unmute preview':'Mute preview'} onClick={()=>setMuted(!muted)}>{muted?<VolumeX/>:<Volume2/>}</Button></div>
  {error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
  <div className="grid gap-4 sm:grid-cols-2"><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-border p-4"><input type="checkbox" checked={prefs.enabled} onChange={e=>patch({enabled:e.target.checked})} className="size-4 accent-primary"/><span><span className="block text-sm font-medium">Use in new videos</span><span className="text-xs text-muted-foreground">AI adds it to relevant story moments.</span></span></label><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-border p-4"><input type="checkbox" checked={prefs.soundEnabled} onChange={e=>patch({soundEnabled:e.target.checked})} className="size-4 accent-primary"/><span><span className="block text-sm font-medium">Template sound effects</span><span className="text-xs text-muted-foreground">Paper, marker, pencil and soft accents.</span></span></label></div>
  <div className="flex flex-wrap items-center gap-3"><label htmlFor="press-intensity" className="text-sm">Camera movement</label><select id="press-intensity" value={prefs.intensity} onChange={e=>patch({intensity:e.target.value as typeof prefs.intensity})} className="rounded-lg border border-input bg-background px-3 py-2 text-sm"><option value="cinematic">Cinematic</option><option value="subtle">Subtle</option></select></div>
  <p className="text-xs leading-5 text-muted-foreground">Scene headlines, images and source credits come from your video. The preview uses a fictional portrait. Save your channel settings to apply this template to future videos.</p>
  {(template.audioCues??[]).map((cue,i)=><NativeCueAudio key={i} cue={{id:`press-preview-${i}`,startSec:cue.at,durationSec:({ 'press-paper':.8,'press-impact':1.1,'press-marker':.62,'press-whoosh':.76,'press-pencil':.9,'press-rise':1.6,'press-exit':.55} as Record<string,number>)[cue.sound]??.5,file:`motion-${cue.sound}.wav`,gain:cue.gain}} timeSec={time} playing={playing} speed={1} volume={muted?0:1}/>)}
 </section></>;
}
