import type { HtmlTemplate, HtmlTemplateAsset, TemplateLayerEdit } from '@hanuman/shared-types';
export const PRESS_CUTOUT_TEMPLATE_ID = 'press-cutout-v1';
export const PRESS_CUTOUT_CUES: NonNullable<HtmlTemplate['audioCues']> = [
 {at:.12,sound:'press-paper',gain:.40},{at:.45,sound:'press-impact',gain:.32},{at:1.25,sound:'press-marker',gain:.34},
 {at:2,sound:'press-whoosh',gain:.34},{at:3.4,sound:'press-pencil',gain:.30},{at:6,sound:'press-rise',gain:.24},{at:9.4,sound:'press-exit',gain:.30},
];
export function createPressCutoutTemplate(options: {profileId?:string;soundEnabled?:boolean;intensity?:'subtle'|'cinematic'} = {}): HtmlTemplate {
 return {id:PRESS_CUTOUT_TEMPLATE_ID,profileId:options.profileId??'preview',name:'Press Cutout',description:'A documentary headline brought to life with paper, portrait collage, marker highlights and editorial camera movement.',tags:['documentary','editorial','paper'],html:'<div data-template="press-cutout-v1"></div>',css:'',js:'',durationSec:10,assets:[{key:'subject',kind:'image',url:'/motion/press-cutout/portrait.png',required:true}],aiEnabled:true,audioCues:options.soundEnabled===false?[]:PRESS_CUTOUT_CUES.map(c=>({...c}))};
}
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function createPressCutoutDocument({scene={},assets=[],durationSec=10,edits={},gsapSource=''}:{scene?:Record<string,unknown>;assets?:HtmlTemplateAsset[];durationSec?:number;edits?:Record<string,TemplateLayerEdit>;gsapSource?:string}):string {
 const text=(key:string,fallback:string)=>esc(edits[key]?.text??scene[key]??fallback);
 const title=String(edits.title?.text??scene.title??'The minds that changed our world');
 const phrase=String(scene.highlight??title.split(' ').slice(-3).join(' '));
 const index=title.toLowerCase().indexOf(phrase.toLowerCase());
 const heading=index<0?esc(title):`${esc(title.slice(0,index))}<mark><span class="marker"></span><span>${esc(title.slice(index,index+phrase.length))}</span></mark>${esc(title.slice(index+phrase.length))}`;
 const image=String(scene.imageUrl??assets.find(a=>a.key==='subject')?.url??'');
 const safeImage=/^(data:image\/(png|jpeg|webp);base64,|https?:\/\/|\/)/i.test(image)?image:'';
 const config=JSON.stringify({duration:Math.max(1,Math.min(120,durationSec)),cinematic:(scene.motion_intensity??scene.intensity)!=='subtle',edits}).replace(/</g,'\\u003c');
 return `<!doctype html><html><head><meta charset="utf-8"><style>
 @font-face{font-family:PressSerif;src:url('/fonts/engine/Lora-Bold.ttf');font-weight:700;font-display:block}@font-face{font-family:PressText;src:url('/fonts/engine/Lora-Regular.ttf');font-display:block}@font-face{font-family:PressSans;src:url('/fonts/engine/Inter-Regular.ttf');font-display:block}
 *{box-sizing:border-box}html,body{width:1920px;height:1080px;margin:0;overflow:hidden;background:#e9e5dc}body{font-family:PressText,Georgia,serif;color:#1d211f}.camera{position:absolute;inset:-50px;transform-origin:53% 52%;perspective:1800px}.paper{position:absolute;inset:0;background:radial-gradient(ellipse at 23% 20%,#fcfaf1 0,transparent 65%),linear-gradient(127deg,#e1ddd2 0,#f2eee3 48%,#dfdace 100%);box-shadow:inset 0 0 200px #958c7550}.paper:before{content:'';position:absolute;inset:0;opacity:.12;background-image:var(--paper-noise);mix-blend-mode:multiply}.paper:after{content:'';position:absolute;inset:0;background:linear-gradient(162deg,transparent 46%,#887e6320 46.2%,transparent 46.6%),linear-gradient(70deg,transparent 67%,#887e6314 67.1%,transparent 67.5%)}
 .grid{position:absolute;inset:90px;background-image:radial-gradient(#776f6142 .9px,transparent .9px);background-size:28px 28px;opacity:.38}.content{position:absolute;left:166px;top:155px;width:1210px}.kicker{font-family:PressSans,sans-serif;font-size:18px;letter-spacing:4px;text-transform:uppercase;color:#595e55;display:flex;align-items:center;gap:22px;margin-bottom:42px}.kicker:after{content:'';height:1px;width:150px;background:#9b9c8c}.date{display:inline-block;background:#b52e39;color:#fff7ea;font-size:24px;padding:13px 22px;box-shadow:4px 5px 0 #79232922;transform:rotate(-1.5deg);margin-bottom:24px}.headline{font-family:PressSerif,Georgia,serif;font-size:88px;line-height:1.14;letter-spacing:-3px;max-width:1230px;margin:0;position:relative;z-index:3}.headline.long{font-size:70px;letter-spacing:-2px}mark{background:transparent;color:inherit;position:relative;display:inline-block;box-decoration-break:clone;-webkit-box-decoration-break:clone}mark>span:last-child{position:relative;z-index:1}.marker{position:absolute;inset:8% -9px 0;background:#e9e837;transform-origin:left;transform:rotate(-1deg);opacity:.85;z-index:0;clip-path:polygon(0 5%,98% 0,100% 93%,1% 100%)}.bodycopy{font-size:28px;line-height:1.55;max-width:830px;margin-top:30px;position:relative;z-index:4}.credit{font-family:PressSans,sans-serif;font-size:18px;letter-spacing:1.5px;margin-top:27px;display:flex;align-items:center;gap:17px}.credit:before{content:'';height:2px;width:42px;background:#b52e39}.portrait{position:absolute;right:98px;bottom:-38px;width:830px;height:870px;transform-origin:50% 95%;z-index:2;filter:drop-shadow(3px 0 #b52e39) drop-shadow(-3px 0 #b52e39) drop-shadow(0 -3px #b52e39) drop-shadow(18px 18px 0 #65563c22)}.portrait img{width:100%;height:100%;object-fit:contain;object-position:bottom;filter:grayscale(1) contrast(1.08)}.portrait.photo{width:640px;height:510px;right:115px;bottom:135px;padding:18px 18px 55px;background:#f9f6ee;transform:rotate(4deg);box-shadow:0 20px 40px #423e3033;filter:none}.portrait.photo img{object-fit:cover;object-position:center}.scribble{position:absolute;right:92px;top:490px;width:300px;height:170px;z-index:5;fill:none;stroke:#b52e39;stroke-width:5;stroke-linecap:round;stroke-linejoin:round}.rule{height:1px;background:#777c6a;position:absolute;left:165px;right:165px;bottom:100px;transform-origin:left;opacity:.45}.foot{position:absolute;left:165px;bottom:58px;font-family:PressSans;font-size:15px;letter-spacing:2px;color:#69705f}.margin{position:absolute;right:110px;top:132px;font-family:PressSans;font-size:14px;letter-spacing:3px;color:#7b7d70;writing-mode:vertical-rl}.exit{position:absolute;inset:0;background:#f8f5eb;z-index:20;pointer-events:none;opacity:0}
 </style></head><body><div class="camera"><div class="paper"></div><div class="grid"></div><div class="content"><div class="kicker" data-layer-id="kicker">${text('kicker','A closer look')}</div><div class="date" data-layer-id="eyebrow">${text('eyebrow','The story behind the idea')}</div><h1 class="headline ${title.length>75?'long':''}" data-layer-id="title">${heading}</h1><p class="bodycopy" data-layer-id="subtitle">${text('subtitle','Every breakthrough begins with someone willing to ask a different question.')}</p><div class="credit" data-layer-id="source_label">${text('source_label','Illustrative documentary preview')}</div></div><div class="portrait" data-layer-id="subject"><img src="${esc(safeImage)}" alt="" /></div><svg class="scribble" data-layer-id="annotation" viewBox="0 0 300 170"><path d="M260 20 C275 79 189 110 88 93 M88 93 L118 72 M88 93 L117 115"/><path d="M236 8 Q273 19 270 45"/></svg><div class="rule"></div><div class="foot">${text('footer','Research • Context • Perspective')}</div><div class="margin">DOCUMENTARY / VISUAL STORY</div></div><div class="exit"></div><script>${gsapSource.replace(/<\/script/gi,'<\\/script')}</script><script>
 (async function(){const cfg=${config};window.__ready=false;try{if(!window.gsap)throw Error('GSAP runtime missing');for(const selector of ['.date','.credit']){if(!document.querySelector(selector).textContent.trim())document.querySelector(selector).style.display='none';}const grain=document.createElement('canvas');grain.width=256;grain.height=256;const gc=grain.getContext('2d');const pixels=gc.createImageData(256,256);let seed=7193;for(let i=0;i<pixels.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const shade=90+(seed%120);pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=shade;pixels.data[i+3]=100;}gc.putImageData(pixels,0,0);document.documentElement.style.setProperty('--paper-noise','url('+grain.toDataURL()+')');await document.fonts.ready;const img=document.querySelector('.portrait img');if(img.getAttribute('src')){await img.decode();const canvas=document.createElement('canvas');canvas.width=1;canvas.height=1;try{const c=canvas.getContext('2d');c.drawImage(img,0,0,1,1);if(c.getImageData(0,0,1,1).data[3]===255 && !img.src.includes('portrait.png'))document.querySelector('.portrait').classList.add('photo');}catch{document.querySelector('.portrait').classList.add('photo');}}else document.querySelector('.portrait').style.display='none';
 const tl=gsap.timeline({paused:true});const camera=cfg.cinematic?1:0.5;
 tl.from('.camera',{scale:1.13,rotation:-1.8*camera,x:35*camera,y:25*camera,duration:1.05,ease:'power3.out'},0)
 .from('.paper',{opacity:0,duration:.25},0).from('.kicker',{opacity:0,y:12,duration:.5},.15)
 .from('.date',{opacity:0,y:18,rotation:-5,duration:.45,ease:'back.out(1.2)'},.35)
 .from('.headline',{opacity:0,y:38,rotationX:8,duration:.65,ease:'power3.out'},.55)
 .from('.marker',{scaleX:0,duration:.62,ease:'power2.inOut'},1.25)
 .from('.bodycopy',{opacity:0,y:14,duration:.6},1.65)
 .from('.portrait',{opacity:0,y:180,rotation:9*camera,scale:.91,duration:1.1,ease:'power3.out'},2)
 .from('.credit',{opacity:0,x:-18,duration:.45},2.6)
 .from('.rule',{scaleX:0,duration:1,ease:'power2.out'},2.7)
 .from('.foot,.margin',{opacity:0,duration:.5},3);
 document.querySelectorAll('.scribble path').forEach((path,i)=>{const n=path.getTotalLength();gsap.set(path,{strokeDasharray:n,strokeDashoffset:n});tl.to(path,{strokeDashoffset:0,duration:.55,ease:'power2.inOut'},3.4+i*.25);});
 tl.to('.camera',{scale:1.035,rotation:.5*camera,x:-12*camera,y:-10*camera,duration:5.1,ease:'sine.inOut'},4)
 .to('.portrait',{y:-14*camera,duration:4.9,ease:'sine.inOut'},4.1)
 .to('.exit',{opacity:1,duration:.55,ease:'power2.inOut'},9.45);
 const editTransforms=[];for(const [id,edit] of Object.entries(cfg.edits)){const el=Array.from(document.querySelectorAll('[data-layer-id]')).find(e=>e.dataset.layerId===id);if(!el)continue;if(edit.hidden)el.style.visibility='hidden';if(edit.color)el.style.color=edit.color;if(edit.fontSize)el.style.fontSize=edit.fontSize+'px';editTransforms.push([el,edit]);}
 window.__seek=seconds=>{tl.totalTime(Math.max(0,Math.min(10,seconds/cfg.duration*10)),false);for(const [el,e]of editTransforms){el.style.translate=(e.x||0)+'px '+(e.y||0)+'px';el.style.scale=(e.scaleX||1)+' '+(e.scaleY||1);}};window.__seek(0);window.__ready=true;
 }catch(error){window.__error=String(error.message||error);window.__ready=true;}})();
 </script></body></html>`;
}
