import assert from "node:assert/strict";
import { writeFileSync, mkdirSync } from "node:fs";
import { resolve } from "node:path";
import { createEditorState } from "./mock-data";
import { useEditorStore, endGestureHistory } from "./store";
import { buildTimelineManifestV1FromEditorState } from "./build-timeline-manifest";
import { mapTimelineResponseToEditorState } from "./manifest-mapper";
import type { ClipItem } from "./types";
import type { ProjectDetail } from "@/lib/api-client";

process.env.NEXT_PUBLIC_EDITOR_USE_MOCK = "true";
const fixture = createEditorState("00000000-0000-4000-8000-000000000001");
fixture.timeline.id = "00000000-0000-4000-8000-000000000002";
const track = fixture.timeline.tracks.find(t => t.type === "video")!;
const original = track.items[0] as ClipItem;
track.items = [{ ...original, startMs: 0, endMs: 4000, sourceStartMs: 95000, motionTemplate: {id: "editorial-archive", title: "Original archive"} }];
fixture.timeline.tracks = [track];
fixture.timeline.transitions = [];
fixture.timeline.durationMs = 4000;
fixture.project.durationMs = 4000;
fixture.timeline.settings.captionsEnabled = false;
const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="800" height="600"><rect width="800" height="600" fill="#193c50"/><circle cx="400" cy="260" r="180" fill="#e1ad54"/><path d="M0 600L290 250L800 600" fill="#436e64"/><text x="400" y="540" text-anchor="middle" font-size="38" fill="white">REPLACED IMAGE</text></svg>';
fixture.assets.push({ id: "replacement", mediaType: "image", sourceType: "local", label: "Replacement artwork", url: `data:image/svg+xml,${encodeURIComponent(svg)}`, thumbnailUrl: "" });
useEditorStore.setState(structuredClone(fixture));
const getClip = () => useEditorStore.getState().timeline.tracks[0].items[0] as ClipItem;
const edited = { id: "editorial-archive" as const, title: "A story we can edit", subtitle: "Custom text, typography, media and a live clock survive saving and rendering.", eyebrow: "ARCHIVE / 2026", source_label: "Template editing proof", title_style: { font_family: "Arial, Helvetica, sans-serif", font_size: 94, font_weight: 700, color: "#175a70", alignment: "left" as const }, counter: { from: 90, to: 0, format: "clock" as const, prefix: "TIME " } };
useEditorStore.getState().updateClipMotionTemplate(original.id, edited);
endGestureHistory();
useEditorStore.getState().undo();
assert.equal(getClip().motionTemplate?.title, "Original archive");
useEditorStore.getState().redo();
assert.deepEqual(getClip().motionTemplate, edited);
useEditorStore.getState().replaceMedia(original.id, "replacement");
assert.equal(getClip().sourceStartMs, 0, "Replacement media must start at its own beginning");
assert.equal(getClip().motionTemplate?.title, edited.title, "Replacing media preserves template edits");
endGestureHistory();
const state = useEditorStore.getState();
const manifest = buildTimelineManifestV1FromEditorState(state.project.id, state);
assert.deepEqual(manifest.tracks.video[0].motion_template, edited);
assert.match(manifest.tracks.video[0].src, /^data:image/);
const document = JSON.parse(JSON.stringify({ project: state.project, timeline: state.timeline, assets: state.assets }));
assert.deepEqual(buildTimelineManifestV1FromEditorState(state.project.id, {...state, ...document}), manifest, "Saved editor document preserves preview/export manifest");
const project = {id: state.project.id, title: "Template proof", formatMode: "documentary", status: "completed", createdAt: new Date().toISOString()} as ProjectDetail;
const restored = mapTimelineResponseToEditorState(project, {artifactId: "proof", manifest: JSON.parse(JSON.stringify(manifest)), mediaUrls: {}}).state;
assert.deepEqual((restored.timeline.tracks.find(t => t.type === "video")!.items[0] as ClipItem).motionTemplate, edited, "Manifest-only reload preserves all customization");
useEditorStore.getState().toggleTrackLocked(track.id);
useEditorStore.getState().updateClipMotionTemplate(original.id, {...edited, title: "Should not change"});
assert.deepEqual(getClip().motionTemplate, edited, "Locked templates reject edits");
if (process.argv.includes("--proof")) {
  const output = resolve("../../video-review/template-editing");
  mkdirSync(output, {recursive: true});
  writeFileSync(resolve(output, "edited-template.props.json"), JSON.stringify({manifest}, null, 2));
}
console.log("Template editing passed: undo/redo, replacement, locks, editor save/reload, manifest reload and export payload.");
