import assert from "node:assert/strict";
import { createThreePreset } from "@hanuman/shared-types";
import { createEditorState } from "./mock-data";
import { useEditorStore, endGestureHistory } from "./store";
import { applyAgentOps, assertAllowedOp } from "./agent/ops";
import { buildTimelineManifestV1FromEditorState } from "./build-timeline-manifest";
import { mapManifestToTimeline } from "./manifest-mapper";
import type { ClipItem } from "./types";

process.env.NEXT_PUBLIC_EDITOR_USE_MOCK = "true";
const fixture = createEditorState("00000000-0000-4000-8000-000000000001");
const track = fixture.timeline.tracks.find(t => t.type === "video")!;
const clip = track.items[0] as ClipItem;
useEditorStore.setState(structuredClone(fixture));
const scene = createThreePreset("orbit");
assert.ok(assertAllowedOp({ op: "update_clip", itemId: clip.id, threeScene: scene }));
assert.equal(assertAllowedOp({ op: "update_clip", itemId: clip.id, threeScene: { ...scene, code: "bad" } }), null);
assert.equal(applyAgentOps([{ op: "update_clip", itemId: clip.id, threeScene: scene }])[0]!.ok, true);
const item = () => useEditorStore.getState().timeline.tracks.flatMap(t => t.items).find(i => i.id === clip.id) as ClipItem;
assert.deepEqual(item().threeScene, scene);
assert.equal(item().muted, true);
const manifest = buildTimelineManifestV1FromEditorState(fixture.project.id, useEditorStore.getState());
assert.deepEqual(manifest.tracks.video.find(c => c.id === clip.id)?.three_scene, scene);
assert.deepEqual((mapManifestToTimeline(manifest, {}).tracks.flatMap(t => t.items).find(i => i.id === clip.id) as ClipItem).threeScene, scene);
const splitId = useEditorStore.getState().splitItem(clip.id, (clip.startMs + clip.endMs) / 2)!;
const split = useEditorStore.getState().timeline.tracks.flatMap(t => t.items).find(i => i.id === splitId) as ClipItem;
assert.deepEqual(split.threeScene, scene);
assert.equal(split.sourceStartMs, (clip.sourceStartMs ?? 0) + (clip.endMs - clip.startMs) / 2);
endGestureHistory();
assert.equal(applyAgentOps([{ op: "update_clip", itemId: clip.id, threeScene: null }])[0]!.ok, true);
assert.equal(item().threeScene, undefined);
console.log("Three.js agent validation, application, export mapping, split continuity and removal passed");
